# Total number of DNS requests per node is qps * namespaces
{{$PODS_PER_NODE := 30}}
{{$PODS_PER_DEPLOYMENT := 5}}
{{$CNPS_PER_DEPLOYMENT := 15 }}
{{$namespaces := MaxInt (DivideInt .Nodes 100) 1}}
{{$QPS := DefaultParam .CL2_QPS 10}}
{{$TimeToLoad := MultiplyInt $namespaces 6}}
# number of deployments is 30 * #nodes / 5
# for 1 node -> 6 deployments x 1 namespace
# for 100 nodes -> 600 deployments x 1 namespace
# for 500 nodes -> 600 deployments x 5 namespaces
# for 1000 nodes -> 600 deployments x 10 namespaces

# Each deployment has #CNPS_PER_DEPLOYMENT CNPs
# pointing to one random deployment within the same namespace

# QPS says how fast deployments and CNPs are created (counts towards both)
{{$totalPods := MultiplyInt .Nodes $PODS_PER_NODE}}
{{$deployments := DivideInt $totalPods $PODS_PER_DEPLOYMENT}}
{{$deploymentsPerNamespace := DivideInt $deployments $namespaces}}

name: load
namespace:
  number: {{$namespaces}}
  deleteAutomanagedNamespaces: false
tuningSets:
- name: default
  globalQPSLoad:
    qps: {{$QPS}}
    burst: 1
- name: RandomizedSaturationTimeLimited
  RandomizedTimeLimitedLoad:
    timeLimit: {{$TimeToLoad}}m

steps:
- module:
    path: ./modules/metrics.yaml
    params:
      action: start

- module:
    path: ../cilium-agent-pprofs.yaml
    params:
      action: start

- module:
    path: /modules/reconcile-objects.yaml
    params:
      actionName: "create"
      namespaces: {{$namespaces}}
      tuningSet: RandomizedSaturationTimeLimited
      operationTimeout: 15m
      replicasPerDeployment: {{$PODS_PER_DEPLOYMENT}}
      deploymentsPerNamespace: {{$deploymentsPerNamespace}}
      cnpsPerDeployment: {{$CNPS_PER_DEPLOYMENT}}

- module:
    path: ../cilium-agent-pprofs.yaml
    params:
      action: gather

- module:
    path: ./modules/metrics.yaml
    params:
      action: gather

- name: Wait no churn
  measurements:
  - Identifier: sleep
    Method: Sleep
    Params:
      duration: 10m
